
import WarpLayout from '@/compent/layout'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      
        <WarpLayout>
        {children}
        </WarpLayout>
        
        </body>
    </html>
  )
}
